from tools.llm import gemini
from agent.prompts import executor_prompt


class Executor:

    def execute(self, user_request, tasks):
        """
        Executes every task generated by the planner
        and returns the complete document.
        """

        document = {}

        for task in tasks:

            print(f"\nGenerating: {task}")

            prompt = executor_prompt(task, user_request)

            content = gemini.generate(
                prompt=prompt,
                task=task
            )

            document[task] = content

        return document

    def improve(self, user_request, document, feedback):
        """
        Improves every section using Reflection feedback.
        """

        print("\nImproving document...\n")

        improved_document = {}

        for section, content in document.items():

            prompt = f"""
You are a senior business consultant.

Improve the following section based on the review feedback.

User Request:
{user_request}

Feedback:
{feedback}

Section:
{section}

Current Content:
{content}

Return ONLY the improved section.
"""

            improved_document[section] = gemini.generate(
                prompt=prompt,
                task=section
            )

        return improved_document


executor = Executor()