# document.py
import os
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


def document_generator(title, document_data):

    os.makedirs("generated_docs", exist_ok=True)

    filepath = os.path.join(
        "generated_docs",
        f"{title}.docx"
    )

    doc = Document()

    heading = doc.add_heading(title, 0)
    heading.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    p = doc.add_paragraph()
    p.add_run("Generated by Autonomous AI Agent\n").bold = True

    for section, content in document_data.items():

        doc.add_heading(section, level=1)

        if not content:
            content = ""

        content = content.strip()

        # Remove duplicate heading if Gemini already generated it

        if content.lower().startswith(section.lower()):

            content = content[len(section):].strip()

            if content.startswith(":"):
                content = content[1:].strip()

        paragraph = doc.add_paragraph()

        run = paragraph.add_run(content)

        run.font.size = Pt(11)

    doc.save(filepath)

    return filepath